### ISSUE TITLE
Contribution Onboarding

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced#389]
## story

As a contributor, I should have a path to contributions. i.e. link to guide, view content of readme, list good first issues.

## proposal

At the moment contributing to open source is a mixed bag. I am proposing that the Repository page provides context on how to get a contribution if no past contributions are present for this repo.

**Comment by bdougie** [comment]
Hear me out:

sauced.yml - name is WIP.

```
onboard:
  chat: /partycorgi
  training: ://link.com 
  path: "..."
  discussionLink: "..."
```
